name: Frontend CD

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t mafatofu/star-fe .

      - name: Push Docker image to Docker Hub
        run: docker push mafatofu/star-fe

      - name: Deploy to GCP
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          script: |
            sudo docker stop $(sudo docker ps -a | grep star-fe | awk '{print $1}') || true
            sudo docker rm $(sudo docker ps -a | grep star-fe | awk '{print $1}') || true
            sudo docker pull mafatofu/star-fe
            sudo docker run -d -p 3001:3001 --name star-fe mafatofu/star-fe
